    - conda env create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file environment.yml
    - conda activate test-environment
    - conda install --yes coverage coveralls flake8# what language the build will be configured for
language: python

# specify what versions of python will be used
# note that all of the versions listed will be tried
python:
    - 3.6
    - 3.7
    - 3.8

# what branches should be evaluated
branches:
    only:
        - master

# list of commands to run to setup the environment
install:
    - conda env create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file environment.yml
    - conda activate test-environment
    - conda install --yes coverage coveralls flake8


# a list of commands to run before the main script
before_script:
    - "flake8 codebase"

# the actual commands to run
script:
    - coverage run -m unittest discover

# generate a coverage report to send to back to user
after_success:
    - coverage report
    - coveralls
